workflows:
  build-and-deploy:
    jobs:
      # 1. Build and push Config Server FIRST
      - build-test-deploy:
          name: deploy-config-server
          service-dir: "configserver"
          gitops-file-name: "config-server"
          manifest-folder: "infrastructure"

      # 2. Build and push Eureka Server SECOND (waits for Config Server)
      - build-test-deploy:
          name: deploy-eureka-server
          service-dir: "eurekaserver"
          gitops-file-name: "eureka-server"
          manifest-folder: "infrastructure"
          requires:
            - deploy-config-server

      # 3. Build remaining Application Microservices LAST (waits for Eureka)
      - build-test-deploy:
          name: deploy-<< matrix.gitops-file-name >>
          matrix:
            parameters:
              service-dir: ["apigateway", "categoryservice", "productservice"]
              gitops-file-name: ["api-gateway", "category-service", "product-service"]
              manifest-folder: ["apps"]
            exclude:
              - service-dir: "apigateway"
                gitops-file-name: "category-service"
              - service-dir: "apigateway"
                gitops-file-name: "product-service"
              - service-dir: "categoryservice"
                gitops-file-name: "api-gateway"
              - service-dir: "categoryservice"
                gitops-file-name: "product-service"
              - service-dir: "productservice"
                gitops-file-name: "api-gateway"
              - service-dir: "productservice"
                gitops-file-name: "category-service"
          requires:
            - deploy-eureka-server